config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions"}

  root :to => "home#index"
  resources :contacts, only: [:new, :create]
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  namespace :backoffice do
    resources :oc_sessions
    resources :expertises
    resources :courses
    resources :students
    resources :sub_tasks
    root 'dashboard#index'
    resources :invoices
    resources :incomes
    resources :expenses
    resources :recurrent_objects
    resources :presta_designations
    resources :quotations
    resources :projects
    resources :contacts
    resources :achievements
    resources :sub_objectives
    resources :objectives
    resources :tasks do
      post '/clone', :to => 'tasks#clone_task'
    end
    resources :tags
    get 'kanban' => 'tasks#kanban'
    resources :companies
    resources :quotation_pdfs, only: [:show]
    resources :invoice_pdfs, only: [:show]
    resources :units
    devise_for :users,  controllers: {
      :registrations => "backoffice/registrations",
    }
    get '/callback', to: 'dashboard#callback', as: 'callback'

    get '/declared_amount', to: 'dashboard#get_declared_amount', as: 'declared_amount'
  end

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :quotation
  belongs_to :company
  belongs_to :user
  belongs_to :income, optional: true
  enum status: {:is_ongoing=>0, :is_paid=>1, :is_canceled=>2, :is_archived=>3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relationships #
  has_many :tasks
  has_many :objectives
  has_many :projects
  has_many :quotations
  has_many :invoices
  has_many :incomes
  has_many :expenses
  has_many :expenses
  has_many :companies
  has_many :contacts


end

app/controllers/backoffice/achievements_controller.rb
class Backoffice::AchievementsController < Backoffice::BackofficeController
  before_action :set_achievement, only: %i[ show edit update destroy ]

  # GET /achievements or /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/1 or /achievements/1.json
  def show
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements or /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, notice: "Achievement was successfully created." }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1 or /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: "Achievement was successfully updated." }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1 or /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: "Achievement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def achievement_params
      params.require(:achievement).permit(:value)
    end
end

app/controllers/backoffice/backoffice_controller.rb
class Backoffice::BackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attributes_params
  SET_ATTRIBUTES_PARAMS_EXCEPT_CONTROLLERS= ['backoffice/dashboard', 'backoffice/quotation_pdfs', 'backoffice/invoice_pdfs']

  before_action :get_tasks_list
  before_action :get_total_incomes_for_current_month
  before_action :get_total_other_incomes_for_current_month
  #before_action :get_current_week_events_from_calendar
  layout 'backoffice'

  def current_controller
    Rails.application.routes.recognize_path(request.env['PATH_INFO'])[:controller]
  end

  def set_attributes_params
    unless SET_ATTRIBUTES_PARAMS_EXCEPT_CONTROLLERS.include?(params[:controller])
      @attributes = Hash.new
      self.class.name.sub("Controller", "").sub("Backoffice::", "").singularize.constantize.columns_hash.each {|key,value| @attributes[key] = value.type.to_s unless key == "id" || key == "created_at" || key == "updated_at" || key == "is_active" || key =="status" || key == "id_pdfmonkey" || key == "total_ttc" || key == "user_id" || key == "parent_expense"}
    end
  end

  def get_tasks_list
    @pro_tasks_list = Task.where(status_id: 3, task_category: "pro", user_id: current_user).order('priority_id desc') || []
    @perso_tasks_list = Task.where(status_id: 3, task_category:"perso", user_id: current_user).order('priority_id desc') || []
  end

  def get_total_incomes_for_current_month
    @total_incomes = Income.where("EXTRACT(MONTH FROM credit_date) = ?", Time.new.month).sum(:amount)
  end

  def get_total_other_incomes_for_current_month
    @total_other_incomes = Income.where("EXTRACT(MONTH FROM credit_date) = ?", Time.new.month).where(income_type: "other").sum(:amount)
  end

end

app/controllers/backoffice/companies_controller.rb
class Backoffice::CompaniesController < Backoffice::BackofficeController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ create new edit ]

  # GET /backoffice/companies or /backoffice/companies.json
  def index
    @companies = Company.where(user_id: current_user)
  end

  # GET /backoffice/companies/1 or /backoffice/companies/1.json
  def show
  end

  # GET /backoffice/companies/new
  def new
    @company = Company.new
  end

  # GET /backoffice/companies/1/edit
  def edit
  end

  # POST /backoffice/companies or /backoffice/companies.json
  def create
    @company = Company.new(company_params)
    @company.city_address = company_params[:city_address].upcase
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to backoffice_company_path(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backoffice/companies/1 or /backoffice/companies/1.json
  def update
    @company.city_address = company_params[:city_address].upcase
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to backoffice_company_path(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backoffice/companies/1 or /backoffice/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :complement_address, :street_address, :zipcode_address, :city_address,:email, :phone, :is_active, :user_id)
    end

  def get_collections
    @collections = []
  end
end

app/controllers/backoffice/contacts_controller.rb
class Backoffice::ContactsController < Backoffice::BackofficeController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[new create edit]

  # GET /backoffice/contacts or /backoffice/contacts.json
  def index
    @contacts = Contact.where(user_id: current_user)
  end

  # GET /backoffice/contacts/1 or /backoffice/contacts/1.json
  def show
  end

  # GET /backoffice/contacts/new
  def new
    @contact = Contact.new
  end

  # GET /backoffice/contacts/1/edit
  def edit
    @contact =  Contact.find(params[:id])
  end

  # POST /backoffice/contacts or /backoffice/contacts.json
  def create
    @contact = Contact.new(contact_params)
    contact_params[:lastname].upcase
    contact_params[:firstname].capitalize
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @backoffice_contacts_path, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backoffice/contacts/1 or /backoffice/contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to backoffice_contacts_url, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backoffice/contacts/1 or /backoffice/contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:lastname, :firstname, :email, :phone, :is_active, :company_id, :user_id)
    end

  def get_collections
    @collections = [Company.all]
  end
end

app/controllers/backoffice/courses_controller.rb
class Backoffice::CoursesController < Backoffice::BackofficeController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ edit update new create ]
  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to backoffice_courses_path, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to backoffice_courses_path, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_coursesbackoffice_backoffice_backoffice_backoffice_backoffice_backoffice_backoffice__url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_collections
      @collections  = []
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:slug, :name, :description)
    end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < Backoffice::BackofficeController
  include Backoffice::DashboardHelper, Backoffice::GoogleApiHelper, Backoffice::ExpensesHelper

  def index
    # if cookies[:code].nil?
    #   authenticate
    # end
    # Month
    @ongoing_invoices = Invoice.where(status: "is_ongoing")
    @futur_incomes = Array.new
    @ongoing_invoices.each do |invoice|
      @futur_incomes.push(invoice.quotation.total_ttc)
    end
    @monthly_sales = Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "ca").sum(:amount)
    @monthly_incomes = Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "other").sum(:amount)
    @monthly_total_charges = calculation_urssaf_cotisations(@monthly_sales) + calculation_cfp(@monthly_sales) + calculation_income_tax(@monthly_sales)

    # Year
    @annual_sales = Income.where(user_id: current_user).where(income_type: "ca").sum(:amount)
    @annual_incomes = Income.where(user_id: current_user).where(income_type: "other").sum(:amount)
    @futur_incomes = @futur_incomes.sum

    CFE_calculation(@annual_sales)
    @total_annual_dues = Expense.where(user_id:current_user.id).where(expense_type: "charge").sum(:amount)
    @total_other_expenses = Expense.where(user_id:current_user.id).where(expense_type: "expense").where('debit_date BETWEEN ? AND ?', Date.today.beginning_of_year, Date.today.end_of_year ).sum(:amount)
    @month_expenses = get_expenses_for_current_month.sum

    # if !cookies[:last_check_sessions].nil? && cookies[:last_check_sessions].to_date < Date.today
    #   get_sessions_for(Date.today.beginning_of_month, Date.today+1.day)
    # end
    @done_sessions_current_month = OcSession.where('session_date BETWEEN ? AND ?', Date.today.beginning_of_month, Date.today.end_of_month)
    #@week_events = get_current_week_events_from_calendar


    # Objectives #rail
    @objectives = Objective.all
  end
  # le ca est considéré comme annuel

  def get_declared_amount
    respond_to do |format|
        format.json { render json: Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "ca").sum(:amount), status: :ok, cached: true}
    end
  end


end

app/controllers/backoffice/expertises_controller.rb
class Backoffice::ExpertisesController < Backoffice::BackofficeController
  before_action :set_expertise, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ edit update new create ]
  # GET /expertises or /expertises.json
  def index
    @expertises = Expertise.all
  end

  # GET /expertises/1 or /expertises/1.json
  def show
  end

  # GET /expertises/new
  def new
    @expertise = Expertise.new
  end

  # GET /expertises/1/edit
  def edit
  end

  # POST /expertises or /expertises.json
  def create
    @expertise = Expertise.new(expertise_params)

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to backoffice_expertises_path, notice: "Expertise was successfully created." }
        format.json { render :show, status: :created, location: @expertise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertises/1 or /expertises/1.json
  def update
    respond_to do |format|
      if @expertise.update(expertise_params)
        format.html { redirect_to backoffice_expertises_path, notice: "Expertise was successfully updated." }
        format.json { render :show, status: :ok, location: @expertise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1 or /expertises/1.json
  def destroy
    @expertise.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_expertises_url, notice: "Expertise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise
      @expertise = Expertise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expertise_params
      params.require(:expertise).permit(:name, :price)
    end

  def get_collections
    @collections  = []
  end
end

app/views/backoffice/invoices/_form.html.erb
<%= form_with(model: backoffice_invoice) do |form| %>
  <% if backoffice_invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(backoffice_invoice.errors.count, "error") %> prohibited this backoffice_invoice from being saved:</h2>

      <ul>
        <% backoffice_invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :payment_deadline %>
    <%= form.datetime_select :payment_deadline %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.datetime_select :delivery_date %>
  </div>

  <div class="field">
    <%= form.label :TVA %>
    <%= form.check_box :TVA %>
  </div>

  <div class="field">
    <%= form.label :deposit %>
    <%= form.check_box :deposit %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/backoffice/invoices/edit.html.erb
<h1>Editing Backoffice Invoice</h1>

<%= render 'backoffice/shared/custom_form',
           model: @invoice,
           object_name: "backoffice_invoice",
           model_params:@attributes,
           collection: @companies || [],
           form_path: backoffice_invoices_path,
           action: "update",
           method: "patch"
%>
<%= link_to 'Show', @backoffice_invoice %> |
<%= link_to 'Back', backoffice_invoices_path %>

app/views/backoffice/invoices/index.html.erb
<h1>Backoffice Invoices</h1>
<div class="card">
  <div class="card-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Numéro de facture</th>
        <th>Société</th>
        <th>Devis associé</th>
        <th>Date de paiement</th>
        <th>Date de livraison</th>
        <th>TVA</th>
        <th>Facture d'accompte</th>
        <th>Montant</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @invoices.each do |invoice| %>
        <%= form_with(url: backoffice_invoice_path(invoice), method: "patch") do |f| %>
          <tr>
            <td class="id" id="<%= invoice.id %>" style="display: none;"></td>
            <td><%= invoice.digit %></td>
            <td><%= invoice.company.name %></td>
            <td><%=link_to invoice.quotation.name, backoffice_quotation_path(invoice.quotation.id) %></td>
            <td><%= invoice.payment_deadline %></td>
            <td><%= invoice.delivery_date %></td>
            <td><%= invoice.TVA %></td>
            <td><%= invoice.deposit %></td>
            <td><%= number_to_currency(invoice.quotation.total_ttc, locale: :fr) %></td>
            <td><%= select_tag "invoice[status]", options_for_select(Invoice.statuses.map {|key, value| [key.titleize, Invoice.statuses.key(value)]}, invoice.status), {:class =>"form-control status w-auto"} %></td>
            <td><%= link_to 'Show', backoffice_invoice_path(invoice) %></td>
            <td><%= link_to 'Télécharger', backoffice_invoice_pdf_path(invoice), target: '_blank' %></td>
            <td><%= link_to 'Edit', edit_backoffice_invoice_path(invoice) %></td>
            <td><%= link_to 'Destroy', backoffice_invoice_path(invoice), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td>
              <div class="modal fade" id="add_incomes_modal_<%=invoice.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Associer les entrées à la facture payée n° <%= invoice.digit %></h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                      <div class="modal-body">
                        <% @incomes.each do |income| %>
                          <div class="input-group mb-3">
                            <div class="input-group-text">
                              <input class="form-check-input mt-0 income_checkbox" id="<%= income.id %>" type="checkbox" name="invoice[income_ids][]"  value="<%= income.id%>" aria-label="Checkbox for following text input">
                            </div>
                            <input type="text" class="form-control income_value" aria-label="Text input with checkbox" readonly value="<%= income.name%> : <%= number_to_currency(income.amount, local: :fr) %>" data-amount="<%= income.amount %>">
                          </div>
                        <% end %>
                        <div class="input-group mb-3">
                          <div class="input-group-text">
                            <input class="form-check-input mt-0 income_checkbox"  type="checkbox" name="invoice[income_ids][]"  value="" aria-label="Checkbox for following text input">
                          </div>
                          <input type="text" class="form-control income_value" aria-label="Text input with checkbox" readonly value="Aucune facture à associer">
                        </div>
                      </div>
                      <div class="modal-footer">
                        <p>Montant total:</p><span id="total_amount"></span>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                      </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Backoffice Invoice', new_backoffice_invoice_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/backoffice/invoices/new.html.erb
<h1>New Backoffice Invoice</h1>

<%= render 'backoffice/shared/custom_form',
           model: @invoice,
           object_name: "invoice",
           model_params:@attributes,
           form_path: backoffice_invoices_path,
           collection: @collections || [],
           action: "create",
           method: "post"
%>

app/views/backoffice/invoices/show.html.erb
<%= render 'backoffice/shared/custom_show',
           model: @invoice,
           object_path: edit_backoffice_invoice_path(@invoice),
           model_params:@attributes,
           back: backoffice_invoices_path
%>