config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions"}

  root :to => "home#index"
  resources :contacts, only: [:new, :create]
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  namespace :backoffice do
    resources :oc_sessions
    resources :expertises
    resources :courses
    resources :students
    resources :sub_tasks
    root 'dashboard#index'
    resources :invoices
    resources :incomes
    resources :expenses
    resources :recurrent_objects
    resources :presta_designations
    resources :quotations
    resources :projects
    resources :contacts
    resources :achievements
    resources :sub_objectives
    resources :objectives
    resources :tasks do
      post '/clone', :to => 'tasks#clone_task'
    end
    resources :tags
    get 'kanban' => 'tasks#kanban'
    resources :companies
    resources :quotation_pdfs, only: [:show]
    resources :invoice_pdfs, only: [:show]
    resources :units
    devise_for :users,  controllers: {
      :registrations => "backoffice/registrations",
    }
    get '/callback', to: 'dashboard#callback', as: 'callback'

    get '/declared_amount', to: 'dashboard#get_declared_amount', as: 'declared_amount'
  end

end

app/models/company.rb
class Company < ApplicationRecord
  # Relationships
  has_many :contacts
  has_many :projects
  has_many :quotations
  has_many :invoices
  belongs_to :user

  # Validations
  validates :name, :presence => true, uniqueness: true
  validates :description, :presence => true, :allow_blank => true
  validates :complement_address, :presence => true, :allow_blank => true
  validates :street_address, :presence => true, :allow_blank => true
  validates :zipcode_address, :presence => true, :allow_blank => true
  validates :city_address, :presence => true, :allow_blank => true
  validates :email, :presence => true, :allow_blank => true
  validates :phone, :presence => true, :allow_blank => true

end

app/models/contact.rb
class Contact < ApplicationRecord
  # Relationships
  belongs_to :company
  belongs_to :user

  # Validations
  validates :lastname, :presence => true, uniqueness: { scope: [:firstname]}
  validates :firstname, :presence => true, uniqueness: { scope: [:lastname]}
  validates :email, :presence => true, :allow_blank => true
  validates :phone, :presence => true, :allow_blank => true
  validates :is_active, :presence => true, :allow_blank => true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :projects
  has_many :students
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_one :recurrent_object, inverse_of: :expense
  belongs_to :user
  accepts_nested_attributes_for :recurrent_object, allow_destroy: true, reject_if: :all_blank
  scope :without_recurrence, -> { left_joins(:recurrent_object).where("expense_id is not null")}
  scope :with_recurrences, -> { left_joins(:recurrent_object).where("expense_id is null") }
end

app/models/expertise.rb
class Expertise < ApplicationRecord
  belongs_to :project, optional: true
end

app/models/income.rb
class Income < ApplicationRecord
  # Relationships
  has_one :recurrent_object, inverse_of: :income
  belongs_to :invoice, optional: true
  belongs_to :user
  accepts_nested_attributes_for :recurrent_object, allow_destroy: true, reject_if: :all_blank
  # Enum

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :quotation
  belongs_to :company
  belongs_to :user
  belongs_to :income, optional: true
  enum status: {:is_ongoing=>0, :is_paid=>1, :is_canceled=>2, :is_archived=>3}
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :contact_mail, :subject, :message

  validates :contact_mail, :subject, :message, :presence => true
  validates :contact_mail, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/objective.rb
class Objective < ApplicationRecord
   # Relationships
   has_many :sub_objectives
   belongs_to :user
   # Enum
   enum status: [:is_draft, :is_ongoing, :is_paused, :is_finished, :is_archived ]
   # Validations
   validates :name, :presence => true, uniqueness: true
   validates :description, :presence => true, :allow_blank => true
   validates :start_date, :presence => true
   validates :end_date, :presence => true, :allow_blank => true
   validates :status, :presence => true

end

app/models/oc_session.rb
class OcSession < ApplicationRecord
  belongs_to :student, counter_cache: true
end

app/models/priority.rb
class Priority < ApplicationRecord
  # Relationships
  has_many :task
  has_many :project

end

app/models/project.rb
class Project < ApplicationRecord
  # Relationships
  belongs_to :company
  has_many :quotations
  has_many :expertises
  belongs_to :user
  has_many :students
  belongs_to :course, optional: true
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  # Relationships
  belongs_to :company
  belongs_to :user
  belongs_to :project, optional: true
  has_one :invoice

  has_many :presta_designations, inverse_of: :quotation
  accepts_nested_attributes_for :presta_designations, allow_destroy: true, reject_if: :all_blank
end

app/models/status.rb
class Status < ApplicationRecord
  # Relationships
  has_many :tasks
  has_many :sub_objectives

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :project, optional: true
  has_many :oc_sessions
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :status
  belongs_to :task
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tasks

  validates :name, :presence => true
  validates :color, :presence => true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :priority
  belongs_to :status
  belongs_to :user
  belongs_to :tag, :optional => true
  belongs_to :sub_objective, :optional => true

  amoeba do
    enable
  end

  has_many :sub_tasks, dependent: :delete_all

  validates :name, :presence => true
  enum task_category: { is_professional: 'pro', is_personal: 'perso' }
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relationships #
  has_many :tasks
  has_many :objectives
  has_many :projects
  has_many :quotations
  has_many :invoices
  has_many :incomes
  has_many :expenses
  has_many :expenses
  has_many :companies
  has_many :contacts


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="row">
  <section id="about_me">
    <h2>A mon sujet</h2>
    <div class="row">
      <div class="col-md-12 p-5">
        <p>Bonjour à tous !</p>
        <p>Moi c'est Julie, 33 ans, installée sur Antibes depuis deux ans maintenant.</p>
        <p>Originaire de la <a href="https://www.ardeche.fr/">patrie du marron glacé</a>, j'ai fait mes premières armes en tant que commercial dans le domaine de l'informatique. Près de 10 ans plus tard, après avoir travaillé pour des grossistes réseaux, infrastructures, sociétés de service ..., j'ai décidé de passer à un nouveau challenge: le développement informatique !</p>
        <p>Grâce à une <a href="https://cefii.fr/formations-professionnelles/formation-developpeur-web-a-distance.html">formation faite à distance</a>  d'un an, j'arrive sur le marché de la programmation en 2017 très enthousiaste et pleine d'énergie.</p>
        <p>Quatre ans plus tard, je décide de capitaliser mes expériences en tant qu'ingénieur commercial, responsable de Business Unit et développeur pour créer JVA-WEB, mon auto-entreprise.</p>
        <p>Depuis, j'ai la chance de pouvoir exercer toutes les activités que j'aime.</p>
        <p>Je suis ainsi mentor pour OpenClassrooms pour les parcours "Attaché commercial" et "Développeur web".</p>
        <p>Je développe des sites et applications internet pour une clientèle TPE/PME.</p>
        <p>Je réponds à des missions de courtes et longues durées proposées via différents canaux comme <a href="https://www.malt.fr/profile/juliedaprato">Malt</a> et <a href="https://www.linkedin.com/in/julie-da-prato-b5277b72">Linkedin</a> par exemple.</p>
        <p>Et parce que j'aime et souhaite retrouver le contact client et la gestion de projet, je me forme sur le métier de chef de projet digital avec OpenClassrooms depuis peu.</p>
        <p>Pour moi la vie est une aventure, et je souhaite en profiter un maximum !</p>
        <p>Pour plus d'informations, n'hésitez pas à me <a href="#contact">contacter</a> ou à télécharger mon CV</p>
      </div>
    </div>
  </section>
</div>

app/views/home/contact.html.erb
<div class="row">
  <section id="contact">
    <h2>Formulaire de contact</h2>
    <%= form_for @message, :url => contact_path do |f| %>
      <div class="mb-3">
        <%= f.label "Adresse e-mail", class:"form-label" %>
        <%= f.text_field :contact_mail, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label "Sujet de votre message", class:"form-label" %>
        <%= f.text_field :subject, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label "Votre message", class:"form-label" %>
        <%= f.text_area :message, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%#= recaptcha_tags theme: 'dark' %>
      </div>
      <%= f.submit "Envoyer !", class:"btn btn-primary"%>
    <% end %>
  </section>
</div>

app/views/home/index.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 p-0">
        <div class="banner">
          <a href="#" class="typewrite" data-period="2000" data-type='["Développement web", "Sites internets", "Référencement", "Accompagnement", "Formation"]'>
          </a>
        </div>
        </div>
    </div>
    <%= render template: "home/services" %>
    <%= render template: "home/projects" %>
    <%= render template: "home/about" %>
    <%= render template: "home/recommandations" %>
    <%= render template: "home/contact" %>
  </div>
</main>
<footer>
  <div class="about p-5">
    <h4>A propos</h4>
    <p>JVA-WEB micro-entreprise</p>
    <p>N°TVA intracommunautaire : FR93892540386</p>
    <p>N°SIRET: 89254038600018</p>
    <p>Icônes conçues par <a href="https://www.freepik.com" target="_blank" title="Freepik">Freepik</a></p>
  </div>
  <div class="social text-center p-5">
    <h4>Retrouvez-moi sur </h4>
    <a href="https://www.linkedin.com/in/julie-da-prato-b5277b72/" target="_blank">
      <%= image_pack_tag "media/images/social_icons/linkedin.png" %>
    </a>
    <a href="https://www.malt.fr/profile/juliedaprato" target="_blank">
      <%= image_pack_tag "media/images/social_icons/malt.svg" %>
    </a>
  </div>
  <p class="text-center">Copyright JVA-Web 2021</p>
</footer>

app/views/home/projects.html.erb
<div class="row">
  <section id="projects">
    <h2>Projets</h2>
    <p class="leader">Un aperçu des derniers projets sur lesquels j'ai travaillé</p>
    <div class="project">
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/giftify.jpg", alt:"giftify", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">Giftify</h3>
          <p class="card-text">Giftify est un site qui permet aux utilisateurs enregistrés de créer des cagnottes et ou soutenir des cagnottes déjà présentes. Les paiements sont gérés par <a href="">Mangopay.</a></p>
          <h4>Contexte technique en bref</h4>
          <ul>
            <li>Application Ruby On Rails version 2.2.7</li>
            <li>Base de données PostGreSQL</li>
            <li>Hébergement sur Heroku</li>
          </ul>
          <h4>Missions réalisées en bref</h4>
          <ul>
            <li>Mise à jour de l'application (version Ruby 2.2.7 vers 3.0.0)</li>
            <li>Mise en conformité du code</li>
            <li>Réécriture des migrations</li>
            <li>Audit de charge et résolution des problèmes liés aux fuites mémoires</li>
            <li>Résolution problème de paiement et bugs divers</li>
            <li>Automatisation de la traduction </li>
            <li>Accompagnement et formation</li>
            <li>Rédaction d'une documentation</li>
          </ul>
        </div>
      </div>
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/aidants.jpg", alt:"aidants", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">Les Aidants</h3>
          <p class="card-text">Le site des aidants est un site qui met à disposition via un moteur de recherche les prestations auxquels ont droit les aidants de la Métropole de Nice. Ce projet est composé d'un site front où l'on retrouve les prestations, la liste des partenaires ... ainsi qu'un espace professionnel dédié aux partenaires, et enfin un backoffice pour les administrateurs du site.</p>
          <h4>Contexte technique en bref</h4>
          <ul>
            <li>Application Ruby On Rails version 2.7.1</li>
            <li>Base de données PostGreSQL</li>
            <li>Hébergement Linux</li>
          </ul>
          <h4>Missions réalisées en bref</h4>
          <ul>
            <li>Développement de l'application front</li>
            <li>Création d'un moteur de recherche dédié</li>
            <li>Développement d'un backoffice complet avec personnalisation du site internet et gestion des statistiques</li>
            <li>Développement d'un espace professionnel</li>
            <li>Gestion de mailing</li>
            <li>Rédaction d'une documentation</li>
          </ul>
        </div>
      </div>
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/immo.jpg", alt:"immo", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">Immobilier Nice Côte d'Azur</h3>
          <p class="card-text">Le site Immobilier Nice Côte d'Azur permet de mettre à disposition des biens en location et vente à la manière de "Se Loger" par exemple. IL possède un front et un backoffice qui permet la gestion des biens mais aussi des différentes offres.</p>
          <h4>Contexte technique en bref</h4>
          <ul>
            <li>Application Ruby On Rails version 2.7.1</li>
            <li>Base de données PostGreSQL</li>
            <li>Hébergement Linux</li>
          </ul>
          <h4>Missions réalisées en bref</h4>
          <ul>
            <li>Développement d'un module de gestion des offres dématérialisées </li>
            <li>Ajout de statistiques</li>
          </ul>
        </div>
      </div>
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/petitemoutaine.png", alt:"immo", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">Petite moutaine</h3>
          <p class="card-text">Petite Moutaine c'est une belle aventure laineuse et des créations uniques. Un site front présente l'artisan et ses produits, et elle a accès à un backoffice qui permet de gérer l'ajout de produit, ses commandes en ligne etc ...</p>
          <h4>Contexte technique en bref</h4>
          <ul>
            <li>Application Ruby On Rails version 3.0.1</li>
            <li>Base de données PostGreSQL</li>
            <li>Hébergement Heroku</li>
          </ul>
          <h4>Missions réalisées (en cours !)</h4>
          <ul>
            <li>Développement de l'application front</li>
            <li>Développement d'un backoffice</li>
            <li>...</li>
          </ul>
        </div>
      </div>
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/cheznatty.png", alt:"immo", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">Chez Natty</h3>
          <p class="card-text">Chez Natty est un site wordpress vitrine qui présente l'activité d'un coiffeur fictif sur Antibes. Il est composé d'un module de prise de rendez-vous et d'un blog.</p>
          <h4>Contexte technique en bref</h4>
          <ul>
            <li>Wordpress</li>
            <li>Base de données MySQL</li>
            <li>Hébergement Heroku</li>
          </ul>
          <h4>Missions réalisées en bref</h4>
          <ul>
            <li>Développement d'un site vitrine pour coiffeur</li>
            <li>Ajout d'un module de prise de rendez-vous</li>
            <li>...</li>
          </ul>
        </div>
      </div>
      <div class="card bg-dark text-white">
        <%= image_pack_tag "media/images/projects/jvaweb.png", alt:"immo", class:"card-img" %>
        <div class="card-img-overlay">
          <h3 class="card-title text-center">JVA Web</h3>
          <p class="card-text">JVA Web est mon dernier né ! Il comprend un site front et un backoffice qui n'a de cesse de s'enrichir. Il me permet de gérer le tout venant (devis, facturation, déclaration URSAFF etc...) qui concerne la plupart des freelances.</p>
          <h4>Contexte technique</h4>
          <ul>
            <li>Ruby 3.0.1</li>
            <li>Base de données PostGreSQL</li>
            <li>Hébergement Heroku</li>
          </ul>
          <h4>Missions réalisées (en cours !)</h4>
          <ul>
            <li>Développement d'un site front</li>
            <li>Développement d'un backoffice</li>
            <li>Intégration multiples API</li>
            <li>Développement de modules de gestion</li>
            <li>...</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

</div>

app/views/home/recommandations.html.erb
<div class="row recommandations">
  <div class="col-lg-12 p-0">
    <div class="glide" id="reco">
      <div class="glide__track" data-glide-el="track">
        <ul class="glide__slides">
          <li class="glide__slide">
            <a target="_blank" href="https://www.malt.fr/profile/juliedaprato#profileMissions">
              <p>Notre collaboration a été fructueuse !</p>
              <p>"Julie est une développeuse qui va au delà de la mission qui lui est confiée, apporte de la plus-value sur les process du client et conseille véritablement sur ses choix techniques et évolutions nécessaires pour la bonne performance de l'application"</p>
              <p>Eric N., directeur de Fiatope</p>
            </a>
          </li>
          <li class="glide__slide">
            <a target="_blank" href="https://www.linkedin.com/in/julie-da-prato-b5277b72">
              <p>Notre collaboration a été fructueuse !</p>
              <p>"Dans son travail chez EnergIT SAS, Julie s'est affirmée par son esprit d'équipe, son sens du détail et sa volonté de réussir. Julie a été une personne clef pour notre société."</p>
              <p>Laurent V., directeur d'EnergIT</p>
            </a>
          </li>
          <li class="glide__slide">
            <a target="_blank" href="https://www.malt.fr/profile/juliedaprato#profileRecommendations">
              <p>Notre collaboration a été fructueuse !</p>
              <p>"Julie a des qualités humaines et professionnelles remarquables. Elle est très investie, contentieuse et force de propositions. Ce fut un réel plaisir de travailler avec elle."</p>
              <p>Patricia C., chef de projet Métropole de Nice Côte d'Azur</p>
            </a>
          </li>
        </ul>
        <% if !browser.device.mobile? %>
          <div class="glide text-center p-5">
            <div class="glide__arrows">
              <button class="glide__arrow glide__arrow--left">Précédent</button>
              <button class="glide__arrow glide__arrow--right">Suivant</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/services.html.erb
<div class="row">
  <section id="services">
    <h2>Services</h2>
    <p class="leader">Une offre flexible pour répondre à des missions courtes ou longues durées</p>
    <div class="demo-card-wrapper">
      <div class="demo-card demo-card--step1">
        <div class="head">
          <div class="number-box">
            <span>01</span>
          </div>
          <h2><span class="small">Web</span>Application</h2>
        </div>
        <div class="body">
          <p>Aujourd'hui avoir un site internet est quasi incontournable, surtout en ces périodes de crise où <a target="_blank" href="https://www.journaldunet.com/ebusiness/commerce/1495689-l-e-commerce-au-temps-du-covid-19/#:~:text=Aujourd'hui%2C%20l'e,de%20dollars%20cette%20m%C3%AAme%20ann%C3%A9e.">l'achat sur internet n'a jamais autant été aussi important.</a></p>
          <p>Vous souhaitez vous mettre au web mais avez peur d'aller trop vite ? Aucun souci vous pouvez parfaitement y aller par étape en commençant par le développement d'un <a href="#">site vitrine</a> qui présente votre activité, puis évoluer petit à petit vers un <a href="#">site marchand</a>.</p>
          <%= image_pack_tag "media/images/icons_front/cloud.svg" %>
        </div>
      </div>

      <div class="demo-card demo-card--step2">
        <div class="head">
          <div class="number-box">
            <span>02</span>
          </div>
          <h2><span class="small">Web</span> Security</h2>
        </div>
        <div class="body">
          <p>Je m'appuie sur le référentiel <a href="https://fr.wikipedia.org/wiki/Open_Web_Application_Security_Project" target="_blank">OWASP</a> ainsi qu'une veille régulière afin d'être au plus proche des meilleures pratiques du WEB en terme de sécurité.</p>
          <p class="card-text">Je peux vous proposer un audit de sécurité si vous le souhaitez.</p>
          <%= image_pack_tag "media/images/icons_front/encrypted.svg" %>
        </div>
      </div>

      <div class="demo-card demo-card--step3">
        <div class="head">
          <div class="number-box">
            <span>03</span>
          </div>
          <h2><span class="small">Web</span> Adaptation</h2>
        </div>
        <div class="body">
          <p>J'interviens pour des missions de courtes et longues durées afin de vous aider dans vos projets. </p>
          <p>Pour chaque prestation, je n'hésite pas à vous apporter mon conseil et à auditer si nécessaire l'application en amont.</p>
          <p class="card-text">Je rédige par ailleurs toujours une documentation claire et exhaustive que je vous remets en fin de mission.</p>
          <%= image_pack_tag "media/images/icons_front/webpage.svg" %>
        </div>
      </div>

      <div class="demo-card demo-card--step4">
        <div class="head">
          <div class="number-box">
            <span>04</span>
          </div>
          <h2><span class="small">Web</span> SEO</h2>
        </div>
        <div class="body">
          <p class="card-text">Je me forme régulièrement aux nouvelles techniques de référencement afin de vous apporter les meilleures solutions pour que votre site soit visible dans la jungle qu'est internet.</p>
          <p class="card-text">Je m'appuie sur des outils réputés et fiables afin de diagnostiquer au mieux les problèmes que vous pourriez rencontrer</p>
          <%= image_pack_tag "media/images/icons_front/bar_graph.svg" %>
        </div>
      </div>

      <div class="demo-card demo-card--step5">
        <div class="head">
          <div class="number-box">
            <span>05</span>
          </div>
          <h2><span class="small">Web</span>Design</h2>
        </div>
        <div class="body">
          <p>Je travaille en collaboration avec une graphiste pour créer vos identités visuelles, logos et chartes graphiques.</p>
          <p>Je peux intégrer des templates comme créer un design from scratch.</p>
          <%= image_pack_tag "media/images/icons_front/link.svg" %>
        </div>
      </div>
    </div>
  </section>
</div>