config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:sessions => "sessions"}

  root :to => "home#index"
  resources :contacts, only: [:new, :create]
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  namespace :backoffice do
    resources :oc_sessions
    resources :expertises
    resources :courses
    resources :students
    resources :sub_tasks
    root 'dashboard#index'
    resources :invoices
    resources :incomes
    resources :expenses
    resources :recurrent_objects
    resources :presta_designations
    resources :quotations
    resources :projects
    resources :contacts
    resources :achievements
    resources :sub_objectives
    resources :objectives
    resources :tasks do
      post '/clone', :to => 'tasks#clone_task'
    end
    resources :tags
    get 'kanban' => 'tasks#kanban'
    resources :companies
    resources :quotation_pdfs, only: [:show]
    resources :invoice_pdfs, only: [:show]
    resources :units
    devise_for :users,  controllers: {
      :registrations => "backoffice/registrations",
    }
    get '/callback', to: 'dashboard#callback', as: 'callback'

    get '/declared_amount', to: 'dashboard#get_declared_amount', as: 'declared_amount'
  end

end

app/controllers/backoffice/achievements_controller.rb
class Backoffice::AchievementsController < Backoffice::BackofficeController
  before_action :set_achievement, only: %i[ show edit update destroy ]

  # GET /achievements or /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/1 or /achievements/1.json
  def show
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements or /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, notice: "Achievement was successfully created." }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1 or /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: "Achievement was successfully updated." }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1 or /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: "Achievement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def achievement_params
      params.require(:achievement).permit(:value)
    end
end

app/controllers/backoffice/backoffice_controller.rb
class Backoffice::BackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attributes_params
  SET_ATTRIBUTES_PARAMS_EXCEPT_CONTROLLERS= ['backoffice/dashboard', 'backoffice/quotation_pdfs', 'backoffice/invoice_pdfs']

  before_action :get_tasks_list
  before_action :get_total_incomes_for_current_month
  before_action :get_total_other_incomes_for_current_month
  #before_action :get_current_week_events_from_calendar
  layout 'backoffice'

  def current_controller
    Rails.application.routes.recognize_path(request.env['PATH_INFO'])[:controller]
  end

  def set_attributes_params
    unless SET_ATTRIBUTES_PARAMS_EXCEPT_CONTROLLERS.include?(params[:controller])
      @attributes = Hash.new
      self.class.name.sub("Controller", "").sub("Backoffice::", "").singularize.constantize.columns_hash.each {|key,value| @attributes[key] = value.type.to_s unless key == "id" || key == "created_at" || key == "updated_at" || key == "is_active" || key =="status" || key == "id_pdfmonkey" || key == "total_ttc" || key == "user_id" || key == "parent_expense"}
    end
  end

  def get_tasks_list
    @pro_tasks_list = Task.where(status_id: 3, task_category: "pro", user_id: current_user).order('priority_id desc') || []
    @perso_tasks_list = Task.where(status_id: 3, task_category:"perso", user_id: current_user).order('priority_id desc') || []
  end

  def get_total_incomes_for_current_month
    @total_incomes = Income.where("EXTRACT(MONTH FROM credit_date) = ?", Time.new.month).sum(:amount)
  end

  def get_total_other_incomes_for_current_month
    @total_other_incomes = Income.where("EXTRACT(MONTH FROM credit_date) = ?", Time.new.month).where(income_type: "other").sum(:amount)
  end

end

app/controllers/backoffice/companies_controller.rb
class Backoffice::CompaniesController < Backoffice::BackofficeController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ create new edit ]

  # GET /backoffice/companies or /backoffice/companies.json
  def index
    @companies = Company.where(user_id: current_user)
  end

  # GET /backoffice/companies/1 or /backoffice/companies/1.json
  def show
  end

  # GET /backoffice/companies/new
  def new
    @company = Company.new
  end

  # GET /backoffice/companies/1/edit
  def edit
  end

  # POST /backoffice/companies or /backoffice/companies.json
  def create
    @company = Company.new(company_params)
    @company.city_address = company_params[:city_address].upcase
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to backoffice_company_path(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backoffice/companies/1 or /backoffice/companies/1.json
  def update
    @company.city_address = company_params[:city_address].upcase
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to backoffice_company_path(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backoffice/companies/1 or /backoffice/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :complement_address, :street_address, :zipcode_address, :city_address,:email, :phone, :is_active, :user_id)
    end

  def get_collections
    @collections = []
  end
end

app/controllers/backoffice/contacts_controller.rb
class Backoffice::ContactsController < Backoffice::BackofficeController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[new create edit]

  # GET /backoffice/contacts or /backoffice/contacts.json
  def index
    @contacts = Contact.where(user_id: current_user)
  end

  # GET /backoffice/contacts/1 or /backoffice/contacts/1.json
  def show
  end

  # GET /backoffice/contacts/new
  def new
    @contact = Contact.new
  end

  # GET /backoffice/contacts/1/edit
  def edit
    @contact =  Contact.find(params[:id])
  end

  # POST /backoffice/contacts or /backoffice/contacts.json
  def create
    @contact = Contact.new(contact_params)
    contact_params[:lastname].upcase
    contact_params[:firstname].capitalize
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @backoffice_contacts_path, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backoffice/contacts/1 or /backoffice/contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to backoffice_contacts_url, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backoffice/contacts/1 or /backoffice/contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:lastname, :firstname, :email, :phone, :is_active, :company_id, :user_id)
    end

  def get_collections
    @collections = [Company.all]
  end
end

app/controllers/backoffice/courses_controller.rb
class Backoffice::CoursesController < Backoffice::BackofficeController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ edit update new create ]
  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to backoffice_courses_path, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to backoffice_courses_path, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_coursesbackoffice_backoffice_backoffice_backoffice_backoffice_backoffice_backoffice__url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_collections
      @collections  = []
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:slug, :name, :description)
    end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < Backoffice::BackofficeController
  include Backoffice::DashboardHelper, Backoffice::GoogleApiHelper, Backoffice::ExpensesHelper

  def index
    # if cookies[:code].nil?
    #   authenticate
    # end
    # Month
    @ongoing_invoices = Invoice.where(status: "is_ongoing")
    @futur_incomes = Array.new
    @ongoing_invoices.each do |invoice|
      @futur_incomes.push(invoice.quotation.total_ttc)
    end
    @monthly_sales = Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "ca").sum(:amount)
    @monthly_incomes = Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "other").sum(:amount)
    @monthly_total_charges = calculation_urssaf_cotisations(@monthly_sales) + calculation_cfp(@monthly_sales) + calculation_income_tax(@monthly_sales)

    # Year
    @annual_sales = Income.where(user_id: current_user).where(income_type: "ca").sum(:amount)
    @annual_incomes = Income.where(user_id: current_user).where(income_type: "other").sum(:amount)
    @futur_incomes = @futur_incomes.sum

    CFE_calculation(@annual_sales)
    @total_annual_dues = Expense.where(user_id:current_user.id).where(expense_type: "charge").sum(:amount)
    @total_other_expenses = Expense.where(user_id:current_user.id).where(expense_type: "expense").where('debit_date BETWEEN ? AND ?', Date.today.beginning_of_year, Date.today.end_of_year ).sum(:amount)
    @month_expenses = get_expenses_for_current_month.sum

    # if !cookies[:last_check_sessions].nil? && cookies[:last_check_sessions].to_date < Date.today
    #   get_sessions_for(Date.today.beginning_of_month, Date.today+1.day)
    # end
    @done_sessions_current_month = OcSession.where('session_date BETWEEN ? AND ?', Date.today.beginning_of_month, Date.today.end_of_month)
    #@week_events = get_current_week_events_from_calendar


    # Objectives #rail
    @objectives = Objective.all
  end
  # le ca est considéré comme annuel

  def get_declared_amount
    respond_to do |format|
        format.json { render json: Income.where('credit_date BETWEEN ? and ?', Date.today.beginning_of_month, Date.today).where(income_type: "ca").sum(:amount), status: :ok, cached: true}
    end
  end


end

app/controllers/backoffice/expertises_controller.rb
class Backoffice::ExpertisesController < Backoffice::BackofficeController
  before_action :set_expertise, only: %i[ show edit update destroy ]
  before_action :get_collections, only: %i[ edit update new create ]
  # GET /expertises or /expertises.json
  def index
    @expertises = Expertise.all
  end

  # GET /expertises/1 or /expertises/1.json
  def show
  end

  # GET /expertises/new
  def new
    @expertise = Expertise.new
  end

  # GET /expertises/1/edit
  def edit
  end

  # POST /expertises or /expertises.json
  def create
    @expertise = Expertise.new(expertise_params)

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to backoffice_expertises_path, notice: "Expertise was successfully created." }
        format.json { render :show, status: :created, location: @expertise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertises/1 or /expertises/1.json
  def update
    respond_to do |format|
      if @expertise.update(expertise_params)
        format.html { redirect_to backoffice_expertises_path, notice: "Expertise was successfully updated." }
        format.json { render :show, status: :ok, location: @expertise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1 or /expertises/1.json
  def destroy
    @expertise.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_expertises_url, notice: "Expertise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise
      @expertise = Expertise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expertise_params
      params.require(:expertise).permit(:name, :price)
    end

  def get_collections
    @collections  = []
  end
end

app/controllers/backoffice/registrations_controller.rb
class Backoffice::RegistrationsController < Devise::RegistrationsController
  layout "backoffice", only: [:edit, :update]
  def new
    super
  end

  def create
    super
  end

  def edit
    @pro_tasks_list = Task.where(status_id: 3, task_category: "pro", user_id: current_user).order('priority_id desc') || []
    @perso_tasks_list = Task.where(status_id: 3, task_category:"perso", user_id: current_user).order('priority_id desc') || []
    super
  end

  def update
    super
  end
end

app/controllers/backoffice/sessions_controller.rb
class Backoffice::SessionsController < Devise::SessionsController
  layout "backoffice", only: [:edit, :update]
  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end
end

app/views/backoffice/dashboard/index.html.erb
<div class="dashboard">
  <div class="container-fluid p-0 ">
    <div class="row mt-2">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <div class="row d-flex justify-content-between">
              <div class="col">
                <h5 class="card-title">Chiffres d'affaire total : </h5>
                <p style="font-size:35px;"><%= number_to_currency(@annual_sales, locale: :fr) %></p>
              </div>
              <div class="col">
                <h5 class="card-title">Autres revenus : </h5>
                <p style="font-size:35px;"><%= number_to_currency(@annual_incomes, locale: :fr) %></p>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <h5 class="card-title">Charges totales annuelles :</h5>
                <p style="font-size:35px;"><%= number_to_currency(@total_annual_dues, local: :fr) %> </p>
              </div>
              <div class="col">
                <h5 class="card-title">Dépenses totales annuelles :</h5>
                <p style="font-size:35px;"><%= number_to_currency(@total_other_expenses, local: :fr) %> </p>
              </div>
              <div class="col">
                <h5 class="card-title">Revenus totaux nets :</h5>
                <p style="font-size:35px;"><%= number_to_currency(@annual_sales +  @annual_incomes - (@total_annual_dues + @total_other_expenses), local: :fr) %></p>
                <p>Soit une moyenne mensuelle de <%= number_to_currency((@annual_sales +  @annual_incomes - (@total_annual_dues + @total_other_expenses))/12, local: :fr) %></p>
              </div>
            </div>
            <h6 class="card-title">Période du 01/01/21 au <%= Date.current.end_of_month.strftime("%d/%m/%y")  %></h6>
            <%= column_chart [
                               {
                                 name: "Chiffre d'affaire",
                                 data: Income.where(income_type: "ca").group_by_month(:credit_date, format: "%b %Y").sum(:amount),
                                 stack: "stack 1"
                               },
                               {
                                 name: "Autres entrées",
                                 data: Income.where(income_type: "other").group_by_month(:credit_date, format: "%b %Y").sum(:amount),
                                 stack: "stack 1"
                               },
                               {
                                 name: "Total mois net",
                                 data: Income.group_by_month(:credit_date, format: "%b %Y").sum(:amount),
                               }
                             ]
            %>
            <a href="<%= backoffice_incomes_path %>" class="btn btn-primary">Détails CA</a>
            <a href="<%= backoffice_expenses_path %>" class="btn btn-primary">Détails charges</a>
          </div>
        </div>
        <div class="card mt-2">
          <div class="card-body">
            <h5 class="card-title"><a href="<%= backoffice_students_path %>">Suivi OpenClassrooms</a></h5>
            <p class="card-text">Pour le mois de <%= t("date.month.#{Date.today.strftime("%B")}").downcase %></p>
            <div class="row">
              <div class="col">
                <h5 class="card-title">Nombre de sessions réalisées</h5>
                <p style="font-size:35px;"><%= @done_sessions_current_month.count %> </p>
              </div>
              <div class="col">
                <h5 class="card-title">CA approximatif mentorat OpenClassrooms</h5>
                <p style="font-size:35px;"><%= @done_sessions_current_month.count * 35 %> €</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-body d-flex flex-md-wrap justify-content-between">
            <section class="w-50">
              <h5 class="card-title">A déclarer</h5>
              <p class="card-text">Pour le mois de <%= t("date.month.#{Date.today.strftime("%B")}").downcase %></p>
              <p style="font-size:35px;"><%= number_to_currency(@monthly_sales, local: :fr)  %></p>
              <p> soit <strong><%= number_to_currency(@monthly_total_charges, local: :fr, precision:0)  %></strong> de cotisations</p>

            </section>
            <section>
              <h5 class="card-title">Autres revenus pour le mois</h5>
              <p class="card-text">Pour le mois de <%= t("date.month.#{Date.today.strftime("%B")}").downcase %></p>
              <p class="w-50" style="font-size:35px;"><%= number_to_currency(@monthly_incomes, local: :fr)  %></p>
            </section>
            <section class="text-center w-100 mt-5">
              <h5 class="card-title">Revenus totaux pour le mois:</h5>
              <p style="font-size:35px;"><%= number_to_currency((@monthly_sales+@monthly_incomes)-@monthly_total_charges, local: :fr)  %></p>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#declaration_urssaf" data-bs-whatever="<%= number_to_currency(@total_incomes, local: :fr)  %>">
                Déclaration URSAFF
              </button>
              <a target="_blank" href="https://authentification-candidat.pole-emploi.fr/connexion/XUI/?realm=%2Findividu&goto=https%3A%2F%2Fauthentification-candidat.pole-emploi.fr%3A443%2Fconnexion%2Foauth2%2Frealms%2Froot%2Frealms%2Findividu%2Fauthorize%3Frealm%3D%252Findividu%26response_type%3Did_token%2520token%26scope%3Dopenid%2520compteUsager%2520profile%2520contexteAuthentification%2520email%2520courrier%2520notifications%2520etatcivil%2520logW%2520individu%2520pilote%2520nomenclature%2520coordonnees%2520navigation%2520reclamation%2520prdvl%2520idIdentiteExterne%2520pole_emploi%2520suggestions%2520actu%2520application_USG_PN073-tdbcandidat_6408B42F17FC872440D4FF01BA6BAB16999CD903772C528808D1E6FA2B585CF2%26client_id%3DUSG_PN073-tdbcandidat_6408B42F17FC872440D4FF01BA6BAB16999CD903772C528808D1E6FA2B585CF2%26state%3DnGvAyPm5H7iP10w3%26nonce%3DSmKs3tw4i-xbYJP8%26redirect_uri%3Dhttps%253A%252F%252Fcandidat.pole-emploi.fr%252Fespacepersonnel%252F#login/" class="btn btn-primary">Déclaration PE</a>
            </section>
          </div>
        </div>
        <div class="card mt-2">
          <div class="card-body">
            <h5 class="card-title">A venir</h5>
            <p class="card-text">Factures en attente de paiement</p>
            <p style="font-size:35px;"><%= number_to_currency(@futur_incomes, local: :fr)  %></p>
            <a href="<%= backoffice_invoices_path %>" class="btn btn-primary">Mes factures</a>
          </div>
        </div>
        <div class="card mt-2">
          <div class="card-body">
            <h5 class="card-title">Dépenses pour le mois de <%= t("date.month.#{Date.today.strftime("%B")}").downcase %></h5>
            <a href="<%= backoffice_expenses_path %>"><p style="font-size:35px;"><%= number_to_currency(@month_expenses, local: :fr)  %></span></p></a>
            <a href="<%= backoffice_expenses_path %>" class="btn btn-primary">Toutes mes dépenses</a>
          </div>
        </div>

      </div>
      <%= render "declaration_ursaff" %>
<!--        <div class="card">-->
<!--          <div class="card-body">-->
<!--            <h5 class="card-title">Chiffres clés</h5>-->
<!--            <p class="card-text">Pour l'année <%#= Date.today.strftime("%Y")%></p>-->
<!--            <table class="table">-->
<!--              <thead>-->
<!--              <tr>-->
<!--                <th scope="col">Type d'obligations</th>-->
<!--                <th scope="col">Montants annuels</th>-->
<!--                <th scope="col">Commentaires</th>-->
<!--                <th scope="col">liens utiles</th>-->
<!--              </tr>-->
<!--              </thead>-->
<!--              <tbody>-->
<!--              <tr>-->
<!--                <td>Cotisations sociales</td>-->
<!--                <td><%#= number_to_currency(@cotisations, local: :fr)  %></td>-->
<!--                <td>Grâce à l'ACRE pas de paiement tout de suite</td>-->
<!--                <td><a target="_blank" href="https://www.service-public.fr/professionnels-entreprises/vosdroits/F23547">Service public</a></td>-->
<!--              </tr>-->
<!--              <tr>-->
<!--                <td>Impôts</td>-->
<!--                <td> <%#= number_to_currency(@income_tax, local: :fr)  %></td>-->
<!--                <td>Impôt libératoire </td>-->
<!--                <td><a target="_blank" href="https://www.service-public.fr/professionnels-entreprises/vosdroits/F23547">Service public</a></td>-->
<!--              </tr>-->
<!--              <tr>-->
<!--                <td>Contribution à la formation pro</td>-->
<!--                <td> <%#= number_to_currency(@cfp, local: :fr)  %></td>-->
<!--                <td> </td>-->
<!--                <td><a target="_blank" href="https://www.service-public.fr/professionnels-entreprises/vosdroits/F23547">Service public</a></td>-->
<!--              </tr>-->
<!--              <tr>-->
<!--                <td colspan="1">Total annuel</td>-->
<!--                <td><%#= number_to_currency(@cotisations + @income_tax + @cfp, local: :fr) %></td>-->
<!--              </tr>-->
<!--              <tr>-->
<!--                <td colspan="1">Total mensuel</td>-->
<!--                <td><%#= number_to_currency((@cotisations + @income_tax + @cfp)/12, local: :fr) %></td>-->
<!--              </tr>-->
<!--              </tbody>-->
<!--            </table>-->
<!--          </div>-->
<!--        </div>-->
      </div>
    </div>
  </div>
<div class="row mt-2">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Suivi des objectifs</h5>
        <% @objectives.each do |objective| %>
          <div class="card mt-2">
            <div class="card-body d-flex flex-wrap justify-content-between">
              <h5 class="card-title w-100"><%= objective.name %></h5>
              <% objective.sub_objectives.each do |sub_objective| %>
                <p><%= sub_objective.name %> : <%= number_to_percentage(sub_objective.progression / sub_objective.value.to_f*100, precision: 0)%></p>
                <div class="progress w-25 mb-1">
                  <div class="progress-bar progress-bar-striped bg-primary w-<%= sub_objective.progression / sub_objective.value.to_i*100 %>" role="progressbar" aria-valuenow="<%= sub_objective.progression / sub_objective.value.to_f*100 %>" aria-valuemin="0" aria-valuemax="<%= sub_objective.progression / sub_objective.value.to_f*100 %>"></div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <a href="<%= backoffice_sub_objectives_path %>" class="btn btn-primary mt-2">Mes sous-objectifs</a>
      </div>
    </div>
  </div>
</div>
  <div class="row mt-2">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Statut compte JVA-Web</h5>
          <h6 class="card-title">Au <%= Date.today.strftime("%d/%m/%Y")  %></h6>
          <a href="<%= backoffice_incomes_path %>" class="btn btn-primary">Ajouter une entrée</a>
          <a href="<%= backoffice_expenses_path %>" class="btn btn-primary">Ajouter une sortie</a>
          <a href="<%= backoffice_objectives_path %>" class="btn btn-primary">Détails des comptes</a>
        </div>
      </div>
    </div>
  </div>
</div>